[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "15s"
  flush_jitter = "0s"
  hostname = "probe-isp-01" 

[[outputs.influxdb_v2]]
  urls = ["http://<url>:<port>"]
  token = # token
  organization = #org
  bucket = #bucket

[[inputs.ping]]
  urls = ["google.com", "ya.ru", "1.1.1.1", "8.8.8.8", "github.com"]
  count = 4
  ping_interval = 1.0
  timeout = 2.0

# [[inputs.http_response]]
#   urls = [
#     "https://google.com",
#     "https://yandex.com"
#   ]
#   response_timeout = "5s"
#   method = "GET"
#   follow_redirects = true

[[inputs.dns_query]]
  servers = ["8.8.8.8", "1.1.1.1"]
  domains = ["google.com"]
  record_type = "A"
  timeout = 2